//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Appointment
    {
        [Key]
        public int appointment_id { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "PatientName")]
        public string patient_name { get; set; }
        public Nullable<int> patient_age { get; set; }
        public string gender { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Contact")]
        public string contact_number { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Appointment Date")]
        public System.DateTime appointment_date { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Time")]
        public string time { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Doctor Name")]
        public string doctor_name { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Department")]
        public string department { get; set; }
    }
}
