//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Doctor
    {
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Department")]
        public string Department { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Doctor Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Degree")]
        public string Degrees { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Contact")]
        public string Contact { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Day")]
        public string Day { get; set; }
        [Required(ErrorMessage = "The field is required")]
        [Display(Name = "Time")]
        public string Time { get; set; }
        [Key]
        public int DocId { get; set; }
    }
}
